# Pytorch Tutorial

### Tensors Basics


A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [1]:
import torch

In [2]:
torch.__version__

'1.8.1+cu102'

In [3]:
torch.cuda.get_device_name()

'GeForce 840M'

In [4]:
import numpy as np

In [5]:
lst = [3,4,5,6]
arr = np.array(lst)

In [6]:
arr.dtype

dtype('int64')

In [7]:
type(arr)

numpy.ndarray

## Convert Numpy to Pytorch Tensors

### using SHIFT+ TAB you can see the function definition

In [9]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [14]:
# Indexing simillar to numpy
#tensors[0]
tensors[:2]

tensor([3, 4])

In [15]:
#### Disadvantage of from numpy. The array and the tensors uses thesame memory location
tensors[3]=100

In [17]:
tensors

tensor([  3,   4,   5, 100])

In [18]:
arr

array([  3,   4,   5, 100])

In [19]:
### prevent this by using torch.tensor

tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100])

In [20]:
tensor_arr[3]=500

In [23]:
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 500])
[  3   4   5 100]


In [24]:
#Zeros and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [26]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [34]:
a = torch.tensor(np.arange(0,15).reshape(5,3))
a[:,1]

tensor([ 1,  4,  7, 10, 13])

## Arithmetic Operations

In [37]:
a = torch.tensor([3,4,5],dtype=torch.float64)
b = torch.tensor([4,5,6],dtype=torch.float64)
print(a+b)

tensor([ 7.,  9., 11.], dtype=torch.float64)


In [38]:
torch.add(a,b)

tensor([ 7.,  9., 11.], dtype=torch.float64)

In [39]:
c = torch.zeros(3) #same shape as output in below calculation.

In [40]:
torch.add(a,b,out=c) #will be stored in c

tensor([ 7.,  9., 11.])

In [41]:
c

tensor([ 7.,  9., 11.])

In [42]:
#### Some more operations
a = torch.tensor([3,4,5],dtype=torch.float64)
b = torch.tensor([4,5,6],dtype=torch.float64)

In [43]:
### tensor [7,9,11]
torch.add(a,b).sum()

tensor(27., dtype=torch.float64)

## Dot Products and Multi Operations

In [44]:
x = torch.tensor([3,4,5],dtype=torch.float)
y = torch.tensor([4,5,6],dtype=torch.float)

In [45]:
x.mul(y)

tensor([12., 20., 30.])

In [46]:
### 3*4+5*4+6*5

In [47]:
x.dot(y)

tensor(62.)

##### Matrix Multiplication

In [48]:
x = torch.tensor([[1,4,2],[1,5,5]],dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]],dtype=torch.float)

In [49]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [50]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [51]:
x@y

tensor([[55., 53.],
        [90., 92.]])